#!/usr/bin/perl

my $interval = 5;
my $cmd = "urlsnarf -n";

my %req_by_srv;
my @servers; # servers in request order
my $chunk_begin = 1;

sub print_reqs
{
    foreach my $srv (@servers)
    {
	my $n = @{$req_by_srv{$srv}};
	printf("%30s [$n]\n", $srv);
#	foreach my $url (@{$req_by_srv{$srv}})
#	{ print "  $url\n"; }
    }
    print "\n";

    %req_by_srv = ();
    @servers = ();
    $chunk_begin = 1;
}
$SIG{ALRM} = sub { print_reqs(); };

open(IN, "exec $cmd |");
while (my $s = <IN>)
#while (my $s = <STDIN>)
{

    # 192.168.1.102 - - [11/Mar/2012:15:24:15 +0100] "GET http://portail.free.fr/im_zapette/mini_17390.jpg HTTP/1.1" - - "http://portail.free.fr/" "Opera/9.80 (X11; Linux i686; U; en) Presto/2.9.168 Version/11.50"
    # 192.168.1.102 - - [11/Mar/2012:15:21:52 +0100] "POST http://www.javascript-coder.com/files/htm-form-tutorial/html-form-tutorial-example-1.html HTTP/1.1" - - "http://www.javascript-coder.com/files/htm-form-tutorial/html-form-tutorial-example-1.html" "Opera/9.80 (X11; Linux i686; U; en) Presto/2.9.168 Version/11.50"
    if ($s =~ m|"GET http://([^/]*)(/[^ ]*) HTTP| ||
	$s =~ m|"POST http://([^/]*)(/[^ ]*) HTTP|)
    {
	my ($srv, $url) = ($1, $2);
	if (!$req_by_srv{$srv})
	{ push(@servers, $srv); }
	push(@{$req_by_srv{$srv}}, $url);

	if ($chunk_begin)
	{
	    $chunk_begin = 0;
	    alarm $interval;
	}
	next;
    }



    
    print $s;
}

# print buffered requests
alarm 0;
print_reqs();
