#!/usr/bin/perl

# Turn off buffering
$|=1;

my $interval = 5;
my $cmd = "urlsnarf -n";

my %req_by_srv;
my @servers; # servers in request order
my $chunk_begin = 1;

open(IN, "exec $cmd |");
while (my $s = <IN>)
#while (my $s = <STDIN>)
{

    # 192.168.1.102 - - [11/Mar/2012:15:24:15 +0100] "GET http://portail.free.fr/im_zapette/mini_17390.jpg HTTP/1.1" - - "http://portail.free.fr/" "Opera/9.80 (X11; Linux i686; U; en) Presto/2.9.168 Version/11.50"
    # 192.168.1.102 - - [11/Mar/2012:15:21:52 +0100] "POST http://www.javascript-coder.com/files/htm-form-tutorial/html-form-tutorial-example-1.html HTTP/1.1" - - "http://www.javascript-coder.com/files/htm-form-tutorial/html-form-tutorial-example-1.html" "Opera/9.80 (X11; Linux i686; U; en) Presto/2.9.168 Version/11.50"
    if ($s =~ m|"GET http://([^/]*)(/[^ ]*) HTTP| ||
	$s =~ m|"POST http://([^/]*)(/[^ ]*) HTTP|)
    {
	my ($srv, $url) = ($1, $2);
	printf("%s|%s\n", $srv, $url);
	next;
    }
    
    print $s;
}

